id: P010748
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1PD137811
  title: བོད་སོག་ཆོས་འབྱུང་།
  author: ''
  volumes:
    343fc743a5b7467abff477678ee0a8f8:
      image_group_id: I1KG13534
      title: ''
      volume_number: 1
      total_pages: 1060
      base_file: v001.txt
